services:
  web:
    image: "${WEB_IMAGE}"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      TEST_ENV: test_env

x-uffizzi-ingress:
  service: web
  port: 80
