services:
  web:
    build: .
    secrets:
      - pg_user
      - pg_password
      - tst
    environment:
      TEST_ENV: test_env

secrets:
  pg_user:
    external: true
    name: "POSTGRES_USER"
  pg_password:
    external: true
    name: "POSTGRES_PASSWORD"
  tst:
    external: true
    name: "test"
  
x-uffizzi:
  ingress:
    service: web
    port: 80
  continuous_preview:
    share_to_github: true
    delete_preview_after: 48h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true

